### PR TITLE
complete html-forms_personal-profile-form challenge

### PR DESCRIPTION
**Pull request by spacedoe**
# Context

This PR aims to tackle [The HTML Forms Personal Profile Challenge](https://github.com/spiced-academy/honey-web-dev/blob/main/sessions/html-forms/challenges-html-forms.md).

# Changes

- [ ] Created personal profile form according to the task.

### CODE REVIEW

**Comment by AntKarpo** [comment]
looks great!  
just some notes, maybe im wrong:
1. since we dont have an id in css we dont really need it in html (but maybe for the future if we want to change it)
2. the color for red (if you want to have red is #ff0000 in the value.
but maybe you have a better eye than me and it's not bright red directly.


but all in all it's (from my perspective) perfect and you could merge it

**Comment by AntKarpo** [comment]
👍

**Comment by spacedoe** [comment]
Hi Anton, thanks for reviewing.  According to the Readme file in the challenge the colour should be #E5430F.

**Comment by spacedoe** [comment]
As for ids, i think we need them for labes, `<label for="">` for tag is using an id="" from <input>.

**Comment by AntKarpo** [comment]
You are right! ^^,

**Pull request merged**
